---
autoinstall:
  version: 1
  apt:
    disable_components: []
    fallback: abort
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches:
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu
      - arches:
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
  updates: security
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: master2
    password: $6$/P/9.xbsbeqPuTB4$KO5xuHKHXRrE2WX5JL1C3mrQ7eDbHIRCCpS6KDWSMQ/I1K4h5o73t6paZHPCaJHoPvRjZ886vAxVm/ng3By89/
    realname: System Administrator
    username: sysadmin
  kernel:
    package: linux-generic
  keyboard:
    layout: dk
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      eno1:
        dhcp4: true
    version: 2
    wifis: {}
  source:
    id: ubuntu-server
    search_drivers: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  user-data:
    # Set TimeZone and Locale
    timezone: Europe/Copenhagen
    locale: dk_DK.UTF-8
    # cloud-init not managing hosts file. only hostname is added
    manage_etc_hosts: localhost
    users:
      - name: sysadmin
        primary_group: users
        groups: [adm, admin]
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: true
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwq6Tgyc7eUC68KMCB/XIEBxLxVKnzl28O8VvGpDNK0AYS10K4CcLTWAmKbKEt1RL0KnyPnxjshpkiA4kL9uHIV9lSTqSdwmb2qvjtZnKj9iltOBk5dPNyF3PNx7MLRETwNXymJ3WMg8vMh15C7QZ20xIb8XI4HqoO5ZX+B+lDm/y9wzwo4jIItBSxC4nywDElRFOakJkKhMv3PV5IZQCLah0DvGp9ET9Vo/bF7QqoJkHEnL7gQVYRbIC/vUK2UMvprgEOQL8cghk/SoaVHz/q8clbHUWMQMu2Q5oRs9D9Q090wsKAtbl5h4YjBWWn+nf0GPjIuiuc875d05RuOwEEcb9BFnxhMPUJf1YWEP4vBa6R4xPa4+UM1ikQAaHxx54BUnkGrBteS3906ch/v4II9HCFGjMp6zClVfMack0j0NK8Qm7D0Jx7RnQgJ4c6c7kssKE7QQ1Pj6s08tN+SezG+WvhVWpXau2GzjPSw1/U8badEZN/cIXcEHCYYqdBGLU= parallels@devmaster
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDsR+jVl1P8yey6D3tC/4BSJeOd/yAP4a+1oS4fXT33BLprOSk4vfAi/KrZlvVWfQnDV1OALz4KnC1xSTfQzzJQ8nZafEBMtLiNRxrcAw7MVTu8BpwjRZhxJqxC5EvKqAb5F92gBS3ci7IatKZjCOUUrbMjYduvP99phL2lUd94lM9JuiO9V9Z1GNsFymyxfFuiqViXn4RT/l4l1+CqdsDdsDAhjNZAbulgPcv+HQgtx2gu4VWdUR28U09Cm8U3UW3dIbPKaeXLbZ8Hu1s/KLb7UKKRHi1+wWgvOlmA64QpCqnaDiPRncaB+FiTsZJfr4YpwxtZ7rvpU3wErBJAqTj1ZuAMlPo4363IUMN/r+imTONKmPc/Vz8jwdkBKMtHMSjBO8M2j5AELBoJliv7IgF7HYVQmALqyKlkEyF2hnG5RIxOAFWQ47Q+qM5caJW7eg6BAINACsIWHFynShNVFoKZOaCWjL+cSH553ExcDwXQ3pc2MPSuwTzxaIea4fGGeHs= soren@Srens-iMac
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUM48vyRwru2YI6TF2G5RY2Is4+VYs4GeDrPpnYeZXFywBZSmP0mhHRGMKHoCiA30na5tzLJ3e25krmcBE2A7ro4pmiZ13v9wiSFw6NFEEWWwScUu59QJ4gYiPbSjl/f8UkyK4KBL9i+JIkZvgdn4ZrjDIM8ctunS6ZelLL4eocv3HyKHHW8g8E6XlrigmDB56SMT74oDNluZWkW6gd/9E8RGkWMd5yw+YFql2BFHJh/xoEvhP6ag4jmhMScGjcQs+vVllym2oBpRLODYlVrETRq5O4IdY9+z+ItR4sH9pIHix3l8GjrTVAo2UYx3YQ1MQsTA1mgTizjAFag1LHnKBzhRRwqId1pHfZAXKrVGmakk7LUYiXOFt0bqvrmIzJEBwvhQte3P9tBzDeAUEpTITXXtoUQ3gY0Xz88dvDLebWL2zLCKNc7/BpeFAu49WAFOeQOe8ptNDhNnWfJY1Zy2OXx1SoX3p+/fUzQGR0iy5d9HKBIFHfG8gqYIupy/NqTs= soren@Sorens-MacBook-Pro.local
  storage:
    config:
    - ptable: gpt
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: false
      id: disk-sda
      type: disk
    - device: disk-sda
      size: 1127219200
      wipe: superblock
      flag: boot
      number: 1
      preserve: false
      grub_device: true
      offset: 1048576
      path: /dev/sda1
      id: partition-0
      type: partition
    - fstype: fat32
      volume: partition-0
      preserve: false
      id: format-0
      type: format
    - device: disk-sda
      size: 2147483648
      wipe: superblock
      number: 2
      preserve: false
      grub_device: false
      offset: 1128267776
      path: /dev/sda2
      id: partition-1
      type: partition
    - fstype: ext4
      volume: partition-1
      preserve: false
      id: format-1
      type: format
    - device: disk-sda
      size: 236788383744
      wipe: superblock
      number: 3
      preserve: false
      grub_device: false
      offset: 3275751424
      path: /dev/sda3
      id: partition-2
      type: partition
    - name: ubuntu-vg
      devices:
      - partition-2
      preserve: false
      id: lvm_volgroup-0
      type: lvm_volgroup
    - name: ubuntu-lv
      volgroup: lvm_volgroup-0
      size: 53687091200B
      wipe: superblock
      preserve: false
      path: /dev/ubuntu-vg/ubuntu-lv
      id: lvm_partition-0
      type: lvm_partition
    - fstype: ext4
      volume: lvm_partition-0
      preserve: false
      id: format-3
      type: format
    - path: /
      device: format-3
      id: mount-3
      type: mount
    - name: lv-var
      volgroup: lvm_volgroup-0
      size: 53687091200B
      wipe: superblock
      preserve: false
      path: /dev/ubuntu-vg/lv-var
      id: lvm_partition-1
      type: lvm_partition
    - fstype: ext4
      volume: lvm_partition-1
      preserve: false
      id: format-4
      type: format
    - path: /var
      device: format-4
      id: mount-4
      type: mount
    - name: lv-storage
      volgroup: lvm_volgroup-0
      size: 53687091200B
      wipe: superblock
      preserve: false
      path: /dev/ubuntu-vg/lv-storage
      id: lvm_partition-2
      type: lvm_partition
    - fstype: ext4
      volume: lvm_partition-2
      preserve: false
      id: format-5
      type: format
    - path: /storage
      device: format-5
      id: mount-5
      type: mount
    - name: lv-0
      volgroup: lvm_volgroup-0
      size: -1
      wipe: superblock
      preserve: false
      path: /dev/ubuntu-vg/lv-0
      id: lvm_partition-3
      type: lvm_partition
    - fstype: ext4
      volume: lvm_partition-3
      preserve: false
      id: format-6
      type: format
    - path: /srv
      device: format-6
      id: mount-6
      type: mount
    - path: /boot
      device: format-1
      id: mount-1
      type: mount
    - path: /boot/efi
      device: format-0
      id: mount-0
      type: mount
