---
autoinstall:
  apt:
    disable_components: []
    fallback: abort
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: node3
    password: $6$Y7uurVEsQ./Gv4Od$Bj6O.5VCy9SGsswFdfVbuIfQs.caGKAFxOHkwgaEtygkRZSJ9gh1pU5oIq8ik6K1NHhewhy7V5jMjhT/cAW/j0
    realname: System Administrator
    username: sysadmin
  kernel:
    package: linux-generic
  keyboard:
    layout: dk
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      eno1:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-server
    search_drivers: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  user-data:
    # Set TimeZone and Locale
    timezone: Europe/Copenhagen
    locale: dk_DK.UTF-8
    # cloud-init not managing hosts file. only hostname is added
    manage_etc_hosts: localhost
    users:
      - name: sysadmin
        primary_group: users
        groups: [adm, admin]
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: true
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwq6Tgyc7eUC68KMCB/XIEBxLxVKnzl28O8VvGpDNK0AYS10K4CcLTWAmKbKEt1RL0KnyPnxjshpkiA4kL9uHIV9lSTqSdwmb2qvjtZnKj9iltOBk5dPNyF3PNx7MLRETwNXymJ3WMg8vMh15C7QZ20xIb8XI4HqoO5ZX+B+lDm/y9wzwo4jIItBSxC4nywDElRFOakJkKhMv3PV5IZQCLah0DvGp9ET9Vo/bF7QqoJkHEnL7gQVYRbIC/vUK2UMvprgEOQL8cghk/SoaVHz/q8clbHUWMQMu2Q5oRs9D9Q090wsKAtbl5h4YjBWWn+nf0GPjIuiuc875d05RuOwEEcb9BFnxhMPUJf1YWEP4vBa6R4xPa4+UM1ikQAaHxx54BUnkGrBteS3906ch/v4II9HCFGjMp6zClVfMack0j0NK8Qm7D0Jx7RnQgJ4c6c7kssKE7QQ1Pj6s08tN+SezG+WvhVWpXau2GzjPSw1/U8badEZN/cIXcEHCYYqdBGLU= parallels@devmaster
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDsR+jVl1P8yey6D3tC/4BSJeOd/yAP4a+1oS4fXT33BLprOSk4vfAi/KrZlvVWfQnDV1OALz4KnC1xSTfQzzJQ8nZafEBMtLiNRxrcAw7MVTu8BpwjRZhxJqxC5EvKqAb5F92gBS3ci7IatKZjCOUUrbMjYduvP99phL2lUd94lM9JuiO9V9Z1GNsFymyxfFuiqViXn4RT/l4l1+CqdsDdsDAhjNZAbulgPcv+HQgtx2gu4VWdUR28U09Cm8U3UW3dIbPKaeXLbZ8Hu1s/KLb7UKKRHi1+wWgvOlmA64QpCqnaDiPRncaB+FiTsZJfr4YpwxtZ7rvpU3wErBJAqTj1ZuAMlPo4363IUMN/r+imTONKmPc/Vz8jwdkBKMtHMSjBO8M2j5AELBoJliv7IgF7HYVQmALqyKlkEyF2hnG5RIxOAFWQ47Q+qM5caJW7eg6BAINACsIWHFynShNVFoKZOaCWjL+cSH553ExcDwXQ3pc2MPSuwTzxaIea4fGGeHs= soren@Srens-iMac
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUM48vyRwru2YI6TF2G5RY2Is4+VYs4GeDrPpnYeZXFywBZSmP0mhHRGMKHoCiA30na5tzLJ3e25krmcBE2A7ro4pmiZ13v9wiSFw6NFEEWWwScUu59QJ4gYiPbSjl/f8UkyK4KBL9i+JIkZvgdn4ZrjDIM8ctunS6ZelLL4eocv3HyKHHW8g8E6XlrigmDB56SMT74oDNluZWkW6gd/9E8RGkWMd5yw+YFql2BFHJh/xoEvhP6ag4jmhMScGjcQs+vVllym2oBpRLODYlVrETRq5O4IdY9+z+ItR4sH9pIHix3l8GjrTVAo2UYx3YQ1MQsTA1mgTizjAFag1LHnKBzhRRwqId1pHfZAXKrVGmakk7LUYiXOFt0bqvrmIzJEBwvhQte3P9tBzDeAUEpTITXXtoUQ3gY0Xz88dvDLebWL2zLCKNc7/BpeFAu49WAFOeQOe8ptNDhNnWfJY1Zy2OXx1SoX3p+/fUzQGR0iy5d9HKBIFHfG8gqYIupy/NqTs= soren@Sorens-MacBook-Pro.local
  storage:
    config:
    - ptable: gpt
      path: /dev/nvme0n1
      wipe: superblock
      preserve: false
      name: 'osdisk'
      grub_device: false
      id: disk-nvme0n1
      type: disk
    - ptable: gpt
      path: /dev/nvme1n1
      wipe: superblock-recursive
      preserve: false
      name: 'datadisk'
      grub_device: false
      id: disk-nvme1n1
      type: disk
    - device: disk-nvme0n1
      size: 1127219200
      wipe: superblock
      flag: boot
      number: 1
      preserve: false
      grub_device: true
      offset: 1048576
      path: /dev/nvme0n1p1
      id: partition-4
      type: partition
    - fstype: fat32
      volume: partition-4
      preserve: false
      id: format-4
      type: format
    - device: disk-nvme0n1
      size: 2147483648
      wipe: superblock
      number: 2
      preserve: false
      grub_device: false
      offset: 1128267776
      path: /dev/nvme0n1p2
      id: partition-5
      type: partition
    - fstype: ext4
      volume: partition-5
      preserve: false
      id: format-5
      type: format
    - device: disk-nvme0n1
      size: 53687091200
      wipe: superblock
      number: 3
      preserve: false
      grub_device: false
      offset: 3275751424
      path: /dev/nvme0n1p3
      id: partition-6
      type: partition
    - fstype: ext4
      volume: partition-6
      preserve: false
      id: format-6
      type: format
    - path: /
      device: format-6
      id: mount-6
      type: mount
    - device: disk-nvme0n1
      size: 107374182400
      wipe: superblock
      number: 4
      preserve: false
      grub_device: false
      offset: 56962842624
      path: /dev/nvme0n1p4
      id: partition-7
      type: partition
    - fstype: ext4
      volume: partition-7
      preserve: false
      id: format-7
      type: format
    - path: /var/lib
      device: format-7
      id: mount-7
      type: mount
    - device: disk-nvme0n1
      size: -1
      wipe: superblock
      number: 5
      preserve: false
      grub_device: false
      offset: 164337025024
      path: /dev/nvme0n1p5
      id: partition-8
      type: partition
    - fstype: ext4
      volume: partition-8
      preserve: false
      id: format-8
      type: format
    - path: /storage
      device: format-8
      id: mount-8
      type: mount
    - device: disk-nvme1n1
      size: -1
      wipe: superblock
      number: 1
      preserve: false
      grub_device: false
      offset: 1048576
      path: /dev/nvme1n1p1
      id: partition-9
      type: partition
    - fstype: ext4
      volume: partition-9
      preserve: false
      id: format-9
      type: format
    - path: /srv
      device: format-9
      id: mount-9
      type: mount
    - path: /boot
      device: format-5
      id: mount-5
      type: mount
    - path: /boot/efi
      device: format-4
      id: mount-4
      type: mount
