---
autoinstall:
  storage:
    grub:
      reorder_uefi: false
    config:
      - ptable: gpt
        path: /dev/sda
        wipe: superblock-recursive
        preserve: false
        name: ''
        grub_device: false
        type: disk
        id: disk-sda
      - device: disk-sda
        size: 1075M
        wipe: superblock
        flag: boot
        number: 1
        preserve: false
        grub_device: true
        path: /dev/sda1
        type: partition
        id: partition-0
      - fstype: fat32
        volume: partition-0
        preserve: false
        type: format
        id: format-0
      - device: disk-sda
        size: 2G
        wipe: superblock
        number: 2
        preserve: false
        grub_device: false
        path: /dev/sda2
        type: partition
        id: partition-1
      - fstype: ext4
        volume: partition-1
        preserve: false
        type: format
        id: format-1
      - device: disk-sda
        size: -1
        wipe: superblock
        number: 3
        preserve: false
        grub_device: false
        path: /dev/sda3
        type: partition
        id: partition-2
      - name: ubuntu-vg
        devices:
          - partition-2
        preserve: false
        type: lvm_volgroup
        id: lvm_volgroup-0
      - name: ubuntu-lv
        volgroup: lvm_volgroup-0
        size: 30G
        wipe: superblock
        preserve: false
        path: /dev/ubuntu-vg/ubuntu-lv
        type: lvm_partition
        id: lvm_partition-0
      - fstype: ext4
        volume: lvm_partition-0
        preserve: false
        type: format
        id: format-3
      - path: /
        device: format-3
        type: mount
        id: mount-3
      - name: lv-data
        volgroup: lvm_volgroup-0
        size: -1
        wipe: superblock
        preserve: false
        path: /dev/ubuntu-vg/lv-data
        type: lvm_partition
        id: lvm_partition-1
      - fstype: ext4
        volume: lvm_partition-1
        preserve: false
        type: format
        id: format-4
      - path: /storage
        device: format-4
        type: mount
        id: mount-4
      - path: /boot
        device: format-1
        type: mount
        id: mount-1
      - path: /boot/efi
        device: format-0
        type: mount
        id: mount-0

  user-data:
    # Set TimeZone and Locale
    timezone: Europe/Copenhagen
    locale: en_US.UTF-8

    # Hostname
    hostname: node1

    # cloud-init not managing hosts file. only hostname is added
    manage_etc_hosts: localhost

    users:
      - name: sysadmin
        primary_group: users
        groups: [adm, admin]
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: true
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwq6Tgyc7eUC68KMCB/XIEBxLxVKnzl28O8VvGpDNK0AYS10K4CcLTWAmKbKEt1RL0KnyPnxjshpkiA4kL9uHIV9lSTqSdwmb2qvjtZnKj9iltOBk5dPNyF3PNx7MLRETwNXymJ3WMg8vMh15C7QZ20xIb8XI4HqoO5ZX+B+lDm/y9wzwo4jIItBSxC4nywDElRFOakJkKhMv3PV5IZQCLah0DvGp9ET9Vo/bF7QqoJkHEnL7gQVYRbIC/vUK2UMvprgEOQL8cghk/SoaVHz/q8clbHUWMQMu2Q5oRs9D9Q090wsKAtbl5h4YjBWWn+nf0GPjIuiuc875d05RuOwEEcb9BFnxhMPUJf1YWEP4vBa6R4xPa4+UM1ikQAaHxx54BUnkGrBteS3906ch/v4II9HCFGjMp6zClVfMack0j0NK8Qm7D0Jx7RnQgJ4c6c7kssKE7QQ1Pj6s08tN+SezG+WvhVWpXau2GzjPSw1/U8badEZN/cIXcEHCYYqdBGLU= parallels@devmaster
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDsR+jVl1P8yey6D3tC/4BSJeOd/yAP4a+1oS4fXT33BLprOSk4vfAi/KrZlvVWfQnDV1OALz4KnC1xSTfQzzJQ8nZafEBMtLiNRxrcAw7MVTu8BpwjRZhxJqxC5EvKqAb5F92gBS3ci7IatKZjCOUUrbMjYduvP99phL2lUd94lM9JuiO9V9Z1GNsFymyxfFuiqViXn4RT/l4l1+CqdsDdsDAhjNZAbulgPcv+HQgtx2gu4VWdUR28U09Cm8U3UW3dIbPKaeXLbZ8Hu1s/KLb7UKKRHi1+wWgvOlmA64QpCqnaDiPRncaB+FiTsZJfr4YpwxtZ7rvpU3wErBJAqTj1ZuAMlPo4363IUMN/r+imTONKmPc/Vz8jwdkBKMtHMSjBO8M2j5AELBoJliv7IgF7HYVQmALqyKlkEyF2hnG5RIxOAFWQ47Q+qM5caJW7eg6BAINACsIWHFynShNVFoKZOaCWjL+cSH553ExcDwXQ3pc2MPSuwTzxaIea4fGGeHs= soren@Srens-iMac
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUM48vyRwru2YI6TF2G5RY2Is4+VYs4GeDrPpnYeZXFywBZSmP0mhHRGMKHoCiA30na5tzLJ3e25krmcBE2A7ro4pmiZ13v9wiSFw6NFEEWWwScUu59QJ4gYiPbSjl/f8UkyK4KBL9i+JIkZvgdn4ZrjDIM8ctunS6ZelLL4eocv3HyKHHW8g8E6XlrigmDB56SMT74oDNluZWkW6gd/9E8RGkWMd5yw+YFql2BFHJh/xoEvhP6ag4jmhMScGjcQs+vVllym2oBpRLODYlVrETRq5O4IdY9+z+ItR4sH9pIHix3l8GjrTVAo2UYx3YQ1MQsTA1mgTizjAFag1LHnKBzhRRwqId1pHfZAXKrVGmakk7LUYiXOFt0bqvrmIzJEBwvhQte3P9tBzDeAUEpTITXXtoUQ3gY0Xz88dvDLebWL2zLCKNc7/BpeFAu49WAFOeQOe8ptNDhNnWfJY1Zy2OXx1SoX3p+/fUzQGR0iy5d9HKBIFHfG8gqYIupy/NqTs= soren@Sorens-MacBook-Pro.local
