---
autoinstall:
  storage:
    grub:
      reorder_uefi: false
    config:
      - ptable: gpt
        path: /dev/sda
        wipe: superblock-recursive
        preserve: false
        name: ''
        grub_device: false
        type: disk
        id: disk-sda
      - device: disk-sda
        size: 1075M
        wipe: superblock
        flag: boot
        number: 1
        preserve: false
        grub_device: true
        path: /dev/sda1
        type: partition
        id: partition-0
      - fstype: fat32
        volume: partition-0
        preserve: false
        type: format
        id: format-0
      - device: disk-sda
        size: 2G
        wipe: superblock
        number: 2
        preserve: false
        grub_device: false
        path: /dev/sda2
        type: partition
        id: partition-1
      - fstype: ext4
        volume: partition-1
        preserve: false
        type: format
        id: format-1
      - device: disk-sda
        size: -1
        wipe: superblock
        number: 3
        preserve: false
        grub_device: false
        path: /dev/sda3
        type: partition
        id: partition-2
      - name: ubuntu-vg
        devices:
          - partition-2
        preserve: false
        type: lvm_volgroup
        id: lvm_volgroup-0
      - name: ubuntu-lv
        volgroup: lvm_volgroup-0
        size: 30G
        wipe: superblock
        preserve: false
        path: /dev/ubuntu-vg/ubuntu-lv
        type: lvm_partition
        id: lvm_partition-0
      - fstype: ext4
        volume: lvm_partition-0
        preserve: false
        type: format
        id: format-3
      - path: /
        device: format-3
        type: mount
        id: mount-3
      - name: lv-data
        volgroup: lvm_volgroup-0
        size: -1
        wipe: superblock
        preserve: false
        path: /dev/ubuntu-vg/lv-data
        type: lvm_partition
        id: lvm_partition-1
      - fstype: ext4
        volume: lvm_partition-1
        preserve: false
        type: format
        id: format-4
      - path: /storage
        device: format-4
        type: mount
        id: mount-4
      - path: /boot
        device: format-1
        type: mount
        id: mount-1
      - path: /boot/efi
        device: format-0
        type: mount
        id: mount-0

  user-data:
    # Set TimeZone and Locale
    timezone: Europe/Copenhagen
    locale: dk_DK.UTF-8

    # Hostname
    hostname: node2

    # cloud-init not managing hosts file. only hostname is added
    manage_etc_hosts: localhost

    users:
      - name: sysadmin
        primary_group: users
        groups: [adm, admin]
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: true
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCb2NGeJYPd5kexB603EPXQTykKHWsFFDCRRXdFjw+XQ6HeR/a+gen4U9I2KcpACGgTUMrqDc3bGgQwv55f9HItjbXp10P0T59uWV6n8y8KW7Gc+SH7kaRP+cXEsGoeR+0qnqqAYzl2j9DfIr2cMo+7Ca1ZoYhW0eEPQDDHviUx2HybmET0y3F1TS3DiL9Opw6tXAsldl69tV9SBzKwyGa5WzTBxoe83XA9CWTtgW/9vJqyF32FyoJzmDliNeVdL6PXav1SxJCzOPt7s0yazOR4c0WklOa9bGxTz7PWzR1mseL96hgTT8iTHCb0XBbdePaojVH4mJnB/a7S5+oT3Jjy/qrbX27XWc77sKNA0ko/mZCy9I89g+O0vYhshkzPXlr3AxMV+OSSLCadPpFrKUyfJoEWHbu5pIn6L4mcHox2g9SRile1mE9h8feGJVvaA9didBmVu5bDWWh1lIPRLQvJtettuu4ozU570cFv15MNEmlYIIwnfyfV663J5AdfOXk= parallels@devmaster
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDsR+jVl1P8yey6D3tC/4BSJeOd/yAP4a+1oS4fXT33BLprOSk4vfAi/KrZlvVWfQnDV1OALz4KnC1xSTfQzzJQ8nZafEBMtLiNRxrcAw7MVTu8BpwjRZhxJqxC5EvKqAb5F92gBS3ci7IatKZjCOUUrbMjYduvP99phL2lUd94lM9JuiO9V9Z1GNsFymyxfFuiqViXn4RT/l4l1+CqdsDdsDAhjNZAbulgPcv+HQgtx2gu4VWdUR28U09Cm8U3UW3dIbPKaeXLbZ8Hu1s/KLb7UKKRHi1+wWgvOlmA64QpCqnaDiPRncaB+FiTsZJfr4YpwxtZ7rvpU3wErBJAqTj1ZuAMlPo4363IUMN/r+imTONKmPc/Vz8jwdkBKMtHMSjBO8M2j5AELBoJliv7IgF7HYVQmALqyKlkEyF2hnG5RIxOAFWQ47Q+qM5caJW7eg6BAINACsIWHFynShNVFoKZOaCWjL+cSH553ExcDwXQ3pc2MPSuwTzxaIea4fGGeHs= soren@Srens-iMac
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUM48vyRwru2YI6TF2G5RY2Is4+VYs4GeDrPpnYeZXFywBZSmP0mhHRGMKHoCiA30na5tzLJ3e25krmcBE2A7ro4pmiZ13v9wiSFw6NFEEWWwScUu59QJ4gYiPbSjl/f8UkyK4KBL9i+JIkZvgdn4ZrjDIM8ctunS6ZelLL4eocv3HyKHHW8g8E6XlrigmDB56SMT74oDNluZWkW6gd/9E8RGkWMd5yw+YFql2BFHJh/xoEvhP6ag4jmhMScGjcQs+vVllym2oBpRLODYlVrETRq5O4IdY9+z+ItR4sH9pIHix3l8GjrTVAo2UYx3YQ1MQsTA1mgTizjAFag1LHnKBzhRRwqId1pHfZAXKrVGmakk7LUYiXOFt0bqvrmIzJEBwvhQte3P9tBzDeAUEpTITXXtoUQ3gY0Xz88dvDLebWL2zLCKNc7/BpeFAu49WAFOeQOe8ptNDhNnWfJY1Zy2OXx1SoX3p+/fUzQGR0iy5d9HKBIFHfG8gqYIupy/NqTs= soren@Sorens-MacBook-Pro.local
