---

########################
# PXE server variables #
########################
kick_start_server: "{{ dmz_ks_server_ip }}"

##########################
# Vault server variables #
##########################
vault_version: 1.17.3

############################
# Grafana server variables #
############################
grafana_version: 7.5.7

############################
# Rancher server variables #
############################
rancher_version: 2.5.8

########################
# NFS server variables #
########################
nfs_server_path: /srv/nfshare
nfs_server_export: "{{ dmz_network_cidr_ipv4 }}(rw,sync,no_subtree_check,no_root_squash)"
