---

# Get list of packages installed
- name: Get list of packages
  package_facts:
    manager: auto

- name: Install common packages
  apt:
    name: "{{ basic_packages }}"
    update_cache: true
    state: present

- name: Blacklist storage devices in multipath configuration
  include_tasks: multipath_blacklist.yml

- name: Copy bash aliases file
  template:
    src: "bash_aliases.j2"
    dest: "~/.bash_aliases"
    mode: 0600
