---
# Group all variables.

# Remote user name
#ansible_connection: ssh 
ansible_ssh_user: sysadmin
ansible_ssh_pass: "Van&chai4"
ansible_ssh_port: 22

ansible_become: yes 
ansible_become_method: sudo
ansible_become_pass: "Van&chai4"

# Ansible ssh private key
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Cluster Lab Architecture
# Whether to use centralized SAN architecture or not
centralized_san: false

#########################
# Network configuration #
#########################
wan_port: enp3s0
wan_network_cidr: 192.168.1.0/24
wan_network_if_ip: 192.168.1.10
wan_network_mask: 255.255.255.0
wan_gw_ip: 192.168.1.254
lan_port: enx00e04c364372
lan_network_cidr: 10.0.1.0/24
lan_network_if_ip: 10.0.1.1
lan_network_mask: 255.255.255.0
lan_gw_ip: 10.0.1.1
dmz_port: enx00e04c680063
dmz_network_cidr: 10.0.2.0/24
dmz_network_if_ip: 10.0.2.1
dmz_network_mask: 255.255.255.0
dmz_gw_ip: 10.0.2.1
wifi_port: wlan0
wifi_network_cidr: 10.0.3.0/24
wifi_network_if_ip: 10.0.3.1
wifi_network_mask: 255.255.255.0
wifi_gw_ip: 10.0.3.1
global_dns1: 108.162.195.90
global_dns2: 162.159.38.251

#####################
# DNS configuration #
#####################
# DNS server
wan_dns_domain: mylabnet.dk
lan_dns_domain: mylabnet.dk
dmz_dns_domain: dmz.mylabnet.dk
wifi_dns_domain: wifi.mylabnet.dk

# TFTP configuration
tftp_dir_path: "/srv/tftp"

################################
# restic backup role variables #
################################
# Deactivate clean service. Only enabled in one node
restic_clean_service: false
restic_backups_dirs:
  - path: '/etc'
  - path: '/root'
    exclude:
      - pattern: '.cache'
  - path: '/home/{{ ansible_user }}'
    exclude:
      - pattern: '.cache'
      - pattern: '.ansible'

##########################
# Security configuration #
##########################
security_lan_network_cidr: '{{ lan_network_cidr }}'
security_dmz_network_cidr: '{{ dmz_network_cidr }}'
security_ssh_allow_users: null
security_ssh_port: '{{ ansible_ssh_port }}'

#############################
# Certmanager configuration #
#############################
certbot_dns_provider: cloudflare

cloudflare_email: soren.sjostrom@hotmail.com
cloudflare_api_key: "{{ vault.certmanager.cloudflare.cloudflare_api_key }}"
cloudflare_api_token: "{{ vault.certmanager.cloudflare.cloudflare_api_token }}"
cloudflare_api_ca_key: "{{ vault.certmanager.cloudflare.cloudflare_api_ca_key }}"
cloudflare_domain: "mylabnet.dk"
