---

- name: Ensure python virtualenv is installed.
  package:
    name:
      - python3-pip
      - python3-venv
    state: present
  become: true
  when: install_python_packages

- name: "Install certbot and {{ certbot_dns_provider }} plugin in virtual environment"
  pip:
    name:
      - certbot
      - "{{ certbot_dns_provider_plugin }}"
    virtualenv: "{{ certbot_venv }}"
    virtualenv_command: "python3 -m venv"
    state: present

- name: Create working directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ certbot_venv }}/logs"
    - "{{ certbot_venv }}/config"

- name: Create secret directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ certbot_venv }}/.secrets"

- name: "Copy {{ certbot_dns_provider }} secret file"
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
    - template: "{{ certbot_dns_provider }}-credentials.ini.j2"
      dest: "{{ certbot_venv }}/.secrets/{{ certbot_dns_provider }}-credentials.ini"

- name: Copy certbot wrapper script
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - template: certbot.sh.j2
      dest: "{{ certbot_venv }}/bin/certbot-create-cert.sh"
    - template: certbot-wrapper.sh.j2
      dest: "{{ certbot_venv }}/bin/certbot-wrapper.sh"
