---

- name: Configure Mini-cluster nodes backup
  hosts: minicluster:pigate
  gather_facts: true
  tags: [backup]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
    # Include minicluster variables
    - name: Include minicluster variables
      include_vars: "vars/minicluster.yml"
    - name: Load CA certificate for restic
      set_fact:
        restic_ca_cert: "{{ lookup('file','certificates/CA.pem') }}"
      when: not enable_letsencrypt
    - name: Do not use CA certificate
      set_fact:
        restic_use_ca_cert: false
      when: enable_letsencrypt
  roles:
    - role: sysadmin.backup
      tags: [backup]
