---

- name: Generate vault variables file
  hosts: localhost

  vars_prompt:
    - name: cloudflare_public_prefix
      prompt: Enter Cloudflare public prefix
      private: false
    - name: cloudflare_secret
      prompt: Enter Cloudflare secret
      private: true

  pre_tasks:
    - name: Ask for SAN centralized credentials
      when: centralized_san
      block:
        - name: Ask for SAN iscsi credentials 1/2
          pause:
            prompt: "Enter iSCSI node password: "
            echo: false
          register: prompt
        - name: Set iSCSI node password variable
          set_fact:
            san_iscsi_node_pass: "{{ prompt.user_input }}"
          no_log: true
        - name: Ask for SAN iscsi credentials 2/2
          pause:
            prompt: "Enter iSCSI mutual password: "
            echo: false
          register: prompt
        - name: Set iSCSI node password variable
          set_fact:
            san_iscsi_mutual_pass: "{{ prompt.user_input }}"
          no_log: true

  tasks:

    - name: Create random passwords
      ansible.builtin.set_fact:
        k3s_token: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        minio_root_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        minio_restic_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        minio_longhorn_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        minio_velero_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        minio_loki_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        minio_tempo_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        traefik_basic_auth_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        fluentd_shared_key: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        grafana_admin_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        elasticsearch_admin_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        elasticsearch_fluentd_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        elasticsearch_prometheus_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        keycloak_admin_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        keycloak_pi_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        keycloak_postgresql_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        oauth2_proxy_client_secret: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        oauth2_proxy_cookie: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        oauth2_proxy_redis_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        grafana_client_secret: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        postgresql_admin_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        mysql_admin_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        mysql_root_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      ansible.builtin.set_fact:
        mysql_user_password: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"

    - name: Encrypt file
      ansible.builtin.command:
        cmd: ansible-vault encrypt --vault-password-file=./.vault/vault-pass.sh vars/vault.yml
