---
# Deploy fluentbit to get logs and prometheus metrics
- name: Deploy fluentbit on control nodes (gateway and devmaster)
  hosts: gateway
  gather_facts: true
  tags: [logging]
  become: true
  pre_tasks:
    # Include vault variables
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
    # Include minicluster variables
    - name: Include minicluster variables
      include_vars: "vars/minicluster.yml"
      tags: ["always"]
  roles:
    - role: logging/external_node
      tags: ['logging']
