---
all:
  children:
    control:
      hosts:
        gateway:
          hostname: minigate
          ansible_host: 10.0.1.1
          ip: 192.168.1.10
          mac: 94:c6:91:1d:72:53
        devmaster:
          hostname: devmaster
          ansible_host: localhost
          ansible_connection: local
    external:
      hosts:
        storage:
    minicluster:
      hosts:
        master1:
          hostname: master1
          ansible_host: 10.0.1.21
          ip: 10.0.1.21
          mac: b8:ae:ed:71:f2:20
        master2:
          hostname: master2
          ansible_host: 10.0.1.22
          ip: 10.0.1.22
          mac: 94:c6:91:14:9a:f7
        node1:
          hostname: node1
          ansible_host: 10.0.2.31
          ip: 10.0.2.31
          mac: 80:ee:73:fa:f4:36
        node2:
          hostname: node2
          ansible_host: 10.0.2.32
          ip: 10.0.2.32
          mac: 80:ee:73:fa:f4:33
        node3:
          hostname: node3
          ansible_host: 10.0.2.33
          ip: 10.0.2.33
          mac: 80:ee:73:fa:f4:1d
        tools1:
          hostname: tools1
          ansible_host: 10.0.2.41
          ip: 10.0.2.41
          mac: 94:c6:91:ad:2f:61
#        tools2:
#          hostname: tools2
#          ansible_host: 10.0.2.42
#          ip: 10.0.2.42
#          mac: c0:3f:d5:6c:e8:9d
    x86:
      hosts:
        master[1:2]:
        node[1:3]:
        tools[1:2]:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            master[1:2]:
        k3s_worker:
          hosts:
            node[1:3]:
