---

- name: Configure Mini Cluster Nodes
  hosts: minicluster
  gather_facts: true
  tags: [node]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
  roles:
    # OS basic setup tasks
    - role: basic_setup
      tags: [os]
  
    # Firewall configuration
    - role: ricsanfre.firewall
      tags: [firewall]

    # Security Hardening
#    - role: sorensj.security
#      tags: [security]

    # NTP Server configuration
    - role: ricsanfre.ntp
      tags: [ntp]

    # Certbot configuration
    - role: certbot
      tags: [certbot]
