---

- name: Configure Mini Cluster Gateway
  hosts: gateway
  gather_facts: true
  tags: [gateway]
  become: true

  pre_tasks:
    - name: Include vault variables
      ansible.builtin.include_vars: "vault.yml"
      tags: ["always"]
    - name: Include gateway variables
      ansible.builtin.include_vars:
        dir: host_vars
        files_matching: gateway.yml
      tags: ["always"]
    - name: Collect facts
      ansible.builtin.setup:
        gather_subset:
          - min
      tags: ["always"]

  tasks:
    - name: Bootstrap configuration
      ansible.builtin.import_role:
        name: robertdebock.roles.bootstrap
      tags:
        - bootstrap

    - name: Core dependencies configuration
      ansible.builtin.import_role:
        name: robertdebock.roles.core_dependencies
      tags:
        - core

    - name: OS basic setup tasks
      ansible.builtin.import_role:
        name: basic_setup
      tags:
        - os

    - name: Include dnsmasq
      ansible.builtin.import_role:
        name: sorensj.dnsmasq
      tags:
        - dnsmasq

#    - name: Security Hardening
#      ansible.builtin.import_role:
#        name: sorensj.security
#      tags:
#        - security

#    - name: Update DNS server to point to DNSmasq
#      ansible.builtin.import_role:
#        name: dns
#      tags:
#        - dns

#    - name: Firewall (nftables) configuration
#      ansible.builtin.import_role:
#        name: ricsanfre.firewall
#      tags:
#        - firewall

#    - name: NTP Server configuration
#      ansible.builtin.import_role:
#        name: ricsanfre.ntp
#      tags:
#        - ntp

#    - name: PXE server
#      ansible.builtin.import_role:
#        name: pxe-server
#      tags:
#        - pxe

