---

- name: Create grub direcorty
  file:
    path: "{{ tftp_dir_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - grub
    - pxelinux.cfg

- name: Copy grub config file
  template:
    src: "templates/grub.conf.j2"
    dest: "{{ tftp_dir_path }}/grub/grub.cfg"

- name: Create autoinstall pxe config file per device
  include_tasks:
    file: create_pxe_config_files.yml
  loop: "{{ groups['x86'] }}"
  loop_control:
    loop_var: x86_host
  when:
    - groups['x86'] is defined
