---
# This is a playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: check for /etc/ssh/ssh_config
    stat:
      path: /etc/ssh/ssh_config
    register: p

  - name: check ssh_config
    assert:
      that:
        - p.stat.exists

  - name: check for /etc/ssh/sshd_config
    stat:
      path: /etc/ssh/sshd_config
    register: p

  - name: check sshd_config
    assert:
      that:
        - p.stat.exists
